[package]
name = "papcio-rs"
version = "0.1.0"
authors = ["Igor <igor_motyka@mail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5"
xmltree = "0.10.2"
regex = "1.4.5"
