[package]
name = "papcio"
version = "0.0.1"
authors = ["Igor <igor_motyka@mail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.4"
xmltree = "0.10.3"
regex = "1.7"
crossterm="0.26"
futures = "0.3"